<?php
class Form {
    public static function all(): array { return Database::query("SELECT f.*,(SELECT COUNT(*) FROM form_submissions fs WHERE fs.form_id=f.id) as submission_count,(SELECT COUNT(*) FROM form_submissions fs WHERE fs.form_id=f.id AND fs.is_read=0) as unread_count FROM forms f ORDER BY f.name ASC"); }
    public static function findById(int $id): ?array { $r=Database::queryOne("SELECT * FROM forms WHERE id=?",[$id]); if(!$r)return null; $r['fields']=Database::query("SELECT * FROM form_fields WHERE form_id=? ORDER BY sort_order ASC",[$id]); return $r; }
    public static function findBySlug(string $slug): ?array { $r=Database::queryOne("SELECT * FROM forms WHERE slug=?",[$slug]); if(!$r)return null; $r['fields']=Database::query("SELECT * FROM form_fields WHERE form_id=? ORDER BY sort_order ASC",[$r['id']]); return $r; }
    public static function create(array $d): int { $now=time(); Database::execute("INSERT INTO forms (name,slug,description,success_message,notify_emails,honeypot_field,rate_limit_max,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",[$d['name'],$d['slug'],$d['description']??null,$d['success_message']??'Thank you!',isset($d['notify_emails'])?json_encode($d['notify_emails']):'[]',$d['honeypot_field']??'website',$d['rate_limit_max']??5,$now,$now]); return Database::lastInsertId(); }
    public static function update(int $id, array $d): void { $sets=[]; $params=[]; foreach(['name','slug','description','success_message','honeypot_field','rate_limit_max'] as $c){if(array_key_exists($c,$d)){$sets[]="{$c}=?";$params[]=$d[$c];}} if(array_key_exists('notify_emails',$d)){$sets[]='notify_emails=?';$params[]=json_encode($d['notify_emails']);} $sets[]='updated_at=?'; $params[]=time(); $params[]=$id; Database::execute("UPDATE forms SET ".implode(',',$sets)." WHERE id=?",$params); }
    public static function delete(int $id): void { Database::execute("DELETE FROM forms WHERE id=?",[$id]); }
    public static function replaceFields(int $id, array $fields): void { Database::transaction(function() use($id,$fields){ Database::execute("DELETE FROM form_fields WHERE form_id=?",[$id]); $stmt=Database::get()->prepare("INSERT INTO form_fields (form_id,name,key,type,placeholder,required,options,sort_order) VALUES(?,?,?,?,?,?,?,?)"); foreach($fields as $i=>$f){$stmt->execute([$id,$f['name'],$f['key'],$f['type'],$f['placeholder']??null,(int)($f['required']??0),isset($f['options'])?json_encode($f['options']):'{}',($f['sort_order']??$i)]);} }); }
}
